source 'http://rubygems.org'

gem 'github-pages', group: :jekyll_plugins
gem 'html-proofer'
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.5.0"

gem "github-pages", group: :jekyll_plugins
# gem 'jekyll-admin', group: :jekyll_plugins
